file_table: tables.json 
template:
  # diretorio que identifica a linguagem de geração
  language: java
  # faz a conversão do tipo configurado em datatype das colunas do arquivo tables.json
  map_datatype: mysql.json
  #nome do arquivo e onde se encontram os arquivos de template
  file_template: 
    name: template.yaml
    directory: templates