file_table: klabin/tables.json 
template:
  # diretorio que identifica a linguagem de geração
  language: java
  # faz a conversão do tipo configurado em datatype das colunas do arquivo tables.json
  map_datatype: mysql.json
  #nome do arquivo e onde se encontram os arquivos de template
  file_template: 
    name: template.yaml
    directory: templates

  # configuraç~eos para salver os arquivos   
   
  file_save:
    ext: java
    directory:

  # variáveis definida nos templtes com seus valores default
  variaveis:
    - variavel:
        key: package_path
        value: br.com.klabin.florestal.matrizinsumos
    - variavel:
        key: share-exception
        value: br.com.klabin.florestal.matrizinsumos


# onde esta o bot que faz a interprertação dos templates:
bot:
  path: bot/jawa/parse_java.py
  module: bot.jawa.parse_java
  classe: ParseJava 